; ==============================================================================
; Cerbios Configuration File (cerbios.ini)
; Injected into root of C:\ drive for Cerbios BIOS customization
; ==============================================================================

[General]
; Enable/Disable boot animation (0 = Off, 1 = On)
CustomBootAnimation = 1

[DashPath]
; Dashboard Boot Priority (1 to 5)
Path1 = \Device\Harddisk0\Partition2\evoxdash.xbe
Path2 = \Device\Harddisk0\Partition2\default.xbe
Path3 = \Device\Harddisk0\Partition1\dashboard\default.xbe
Path4 = \Device\Harddisk0\Partition2\xboxdash.xbe
Path5 = \Device\CdRom0\default.xbe

[Video]
; Force Video Modes (0 = Off / Auto, 1 = On)
ForceProgressive = 0
Force480p = 0
Force720p = 0
ForceWidescreen = 0

[Fan]
; Custom Fan Speed percentage (20 to 100)
FanSpeed = 20

[Audio]
; Play Cerbios Startup Sound (0 = Off, 1 = On)
PlayBootSound = 1
